### ISSUE TITLE
Merge with spawnedshelter?

### ISSUE THREAD

**Issue by elbrujohalcon** [drobakowski/awesome-erlang#18]
You should take a look at [The Spawned Shelter](http://github.com/inaka/spawnedshelter). It contains many (if not all) of the links contained here and its original author (@unbalancedparentheses) also promised to turn that list into an actual website, like [Superhero.js](http://superherojs.com/) at some point.

**Comment by elbrujohalcon** [comment]
@unbalancedparentheses …hey… remember that site you were building? :trollface:

**Comment by unbalancedparentheses** [comment]
@elbrujohalcon yeah, I will do it. But I had too much work last few months. I have to finish a few things and I will do it :D.

**Comment by unbalancedparentheses** [comment]
@elbrujohalcon I have almost finished it: http://spawnedshelter.com/

We should decide which links to include. I will put a link to awesome-erlang, but we should hand pick what to include in spawned shelter. @drobakowski your help is greatly appreciated it in chosing the links. Let's continue the talk in https://github.com/unbalancedparentheses/spawnedshelter.

**Comment by elbrujohalcon** [comment]
@unbalancedparentheses for starters you have 2 _comparison_ sections in there :trollface:

**Comment by unbalancedparentheses** [comment]
@elbrujohalcon yes. the content is wrong. We only need to update the markdown. What I have done up to know is only the design. The site is autogenerated from the markdown so that any dev that doesn't have design skill can change the content of the website.

**Comment by elbrujohalcon** [comment]
Awesome! I'll have the guys at @inaka and probably @esl as well take a look and send you PRs :)

**Comment by drobakowski** [comment]
@elbrujohalcon, @unbalancedparentheses thanks for sharing this really great project! :+1: I've included a link to it with 4918198871b9ee4330141172e954bc02299d9560.
