### ISSUE TITLE
Merge with Erlang Bookmarks?

### ISSUE THREAD

**Issue by dethtron5000** [drobakowski/awesome-erlang#3]
I know they are not totally the same, but there's a similar project here: https://github.com/0xAX/erlang-bookmarks/wiki/Erlang-bookmarks

Maybe the two projects can be coordinated?

**Comment by drobakowski** [comment]
@dethtron5000 thanks again for sharing this project. As you might have noticed, unfortunately I didn't had the time so far to compare the two projects. I've included a link to Erlang Bookmarks with 76dc0db00b424857877e5fa76559d15bfd9231f1 to keep track of this project but I'll close this ticket for now. Please feel free to create some PRs in case you would like to merge some of the links from Erlang Bookmarks.
