### ISSUE TITLE
Is this list dead?

### ISSUE THREAD

**Issue by fogfish** [drobakowski/awesome-erlang#66]
I do not see any activities in PRs.

Should you invite more contributors to projects?

**Comment by drobakowski** [comment]
Hi @fogfish, thanks for your effort with contributions so far. This list is definitely not dead, I was a little busy with different topics lately but starting later today I will merge your PR #65 and the other PRs. I do also have a bunch of other interesting libraries which I will add to this list bit by bit in a couple of days. I'm closing this issue for now, please feel free to reopen it if you have further comments. Thanks again for writing!
